default:
  client: local
  pool: default
  numcpus: 2
  memory: 2048
  # memory: 1024
  disks:
  - size: 30
  protocol: ssh
  nets:
  - default

local:
  host: 127.0.0.1
  protocol: ssh
  memory: 2048
  disks:
  - size: 30
  pool: default
  type: kvm

# TODO kvm (mofoserver)
mofoserver:
  host: kvm.mofo.ovh
  user: jonimofo
  protocol: ssh
  pool: default
  type: kvm

# minio1 = 85
# minio2 = 184
