centos:
  image: CentOS-7-x86_64-GenericCloud.qcow2
  numcpus: 2
  memory: 2048
  disks:
  - size: 30
  reservedns: true
  nets:
  - name: default
  cmds:
  - touch /tmp/test
centos7:
  image: CentOS-7-x86_64-GenericCloud.qcow2
